postgres:
  appName: postgres

  secret:
    name: postgres-secret
    username: root
    password: "1111"
    usernameKey: postgres-root-username
    passwordKey: postgres-root-password

  persistentVolume:
    name: postgres-pv
    size: 1Gi
    accessMode: ReadWriteOnce
    path: /mnt/data

  persistentVolumeClaim:
    name: postgres-pvc
    size: 1Gi
    accessMode: ReadWriteOnce

  deployment:
    name: postgres
    replicas: 1
    image: postgres:latest
    containerName: postgres
    mountPath: /var/lib/postgresql/data

  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "512Mi"

  service:
    name: postgres
    portName: postgres
    port: 5432
    nodePort: 30432
    type: NodePort

pgadmin:
  appName: pgadmin

  secret:
    name: pgadmin-secret
    password: "1111"
    passwordKey: pgadmin-default-password
    
  
  delpoyment:
    name: pgadmin
    replicas: 1
    containerName: pgadmin4
    image: dpage/pgadmin4
    envPort: 80
    envEmail: "arine@admin.com"
    port:
      name: pgadminport
      number: 80
    
  service:
    name: pgadmin
    type: NodePort
    ports: 
      port: 80
      nodePort: 32201