version: "3.8"

services:
  postgis:
    build: .
    ports:
      - 15432:5432
    env_file:
      - .env
    restart: always

  pgadmin:
    image: dpage/pgadmin4:8
    env_file:
      - .env
    ports:
      - "127.0.0.1:5050:80"
    restart: always
    depends_on:
      - postgis
