apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pgadmin.secret.name }}
type: Opaque
data:
  pgadmin-default-password: {{ .Values.pgadmin.secret.password | b64enc }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.pgadmin.delpoyment.name }}
spec:
  selector:
   matchLabels:
    app: {{  .Values.pgadmin.appName }}
  replicas: {{ .Values.pgadmin.delpoyment.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.pgadmin.appName }}
    spec:
      containers:
        - name: {{ .Values.pgadmin.delpoyment.containerName }}
          image: {{ .Values.pgadmin.delpoyment.image }}
          env:
           - name: PGADMIN_DEFAULT_EMAIL
             value: {{  .Values.pgadmin.delpoyment.envEmail }}
           - name: PGADMIN_DEFAULT_PASSWORD
             valueFrom:
                secretKeyRef:
                    key: {{ .Values.pgadmin.secret.passwordKey }}
                    name: {{ .Values.pgadmin.secret.name }}
           - name: PGADMIN_PORT
             value: "{{ .Values.pgadmin.delpoyment.envPort }}"
          ports:
            - containerPort: {{ .Values.pgadmin.delpoyment.port.number }}
              name: {{ .Values.pgadmin.delpoyment.port.name }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pgadmin.service.name }}
  labels:
    app: {{ .Values.pgadmin.appName }}
spec:
  selector:
    app: {{ .Values.pgadmin.appName }}
  type: {{ .Values.pgadmin.service.type }}
  ports:
   - port: {{ .Values.pgadmin.service.ports.port }}
     nodePort: {{.Values.pgadmin.service.ports.nodePort }}