services:
  postgres:
    build: .
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
    ports:
      - 5432:5432
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@mail.ru
      - PGADMIN_DEFAULT_PASSWORD=1111
    ports:
      - 5050:80
    restart: always